# Generated by Django 6.0.3 on 2026-03-31 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('approvals', '0001_initial'),
        ('bidding', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalaction',
            name='approver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_actions', to=settings.AUTH_USER_MODEL, verbose_name='审批人'),
        ),
        migrations.AddField(
            model_name='approvalnode',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_nodes', to=settings.AUTH_USER_MODEL, verbose_name='指定审批人'),
        ),
        migrations.AddField(
            model_name='approvalnode',
            name='flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='approvals.approvalflow', verbose_name='所属流程'),
        ),
        migrations.AddField(
            model_name='approvalaction',
            name='node',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='approvals.approvalnode', verbose_name='审批节点'),
        ),
        migrations.AddField(
            model_name='approvalrecord',
            name='bid_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_records', to='bidding.bidsubmission', verbose_name='投标提交'),
        ),
        migrations.AddField(
            model_name='approvalrecord',
            name='current_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_records', to='approvals.approvalnode', verbose_name='当前节点'),
        ),
        migrations.AddField(
            model_name='approvalrecord',
            name='flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='approvals.approvalflow', verbose_name='审批流程'),
        ),
        migrations.AddField(
            model_name='approvalrecord',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_records', to='projects.project', verbose_name='项目'),
        ),
        migrations.AddField(
            model_name='approvalrecord',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_approvals', to=settings.AUTH_USER_MODEL, verbose_name='提交人'),
        ),
        migrations.AddField(
            model_name='approvalaction',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='approvals.approvalrecord', verbose_name='审批记录'),
        ),
    ]
