# Generated by Django 6.0.3 on 2026-03-31 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='项目名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='项目编号')),
                ('description', models.TextField(blank=True, verbose_name='项目描述')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='预算金额(万)')),
                ('period', models.CharField(blank=True, max_length=100, verbose_name='建设周期')),
                ('bid_method', models.CharField(blank=True, max_length=50, verbose_name='招标方式')),
                ('qualifications', models.TextField(blank=True, verbose_name='资质要求')),
                ('bidder', models.CharField(blank=True, max_length=200, verbose_name='招标单位')),
                ('contact', models.CharField(blank=True, max_length=100, verbose_name='联系人')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('region', models.CharField(blank=True, max_length=50, verbose_name='地区')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='项目地址')),
                ('publish_date', models.DateField(blank=True, null=True, verbose_name='发布日期')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='截止日期')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('bidding', '招标中'), ('submitting', '投标中'), ('evaluating', '评标中'), ('completed', '已结束'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='状态')),
                ('risk_level', models.IntegerField(default=50, help_text='0-100，风险越高值越大', verbose_name='风险等级')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '招标项目',
                'verbose_name_plural': '招标项目',
                'db_table': 'projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='编码')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '项目分类',
                'verbose_name_plural': '项目分类',
                'db_table': 'project_categories',
            },
        ),
        migrations.CreateModel(
            name='ProjectRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_type', models.CharField(choices=[('tech', '技术风险'), ('finance', '财务风险'), ('legal', '法律风险'), ('management', '管理风险')], max_length=20, verbose_name='风险类型')),
                ('level', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高')], max_length=10, verbose_name='风险等级')),
                ('score', models.IntegerField(default=50, help_text='0-100', verbose_name='风险评分')),
                ('description', models.TextField(blank=True, verbose_name='风险描述')),
                ('suggestion', models.TextField(blank=True, verbose_name='应对建议')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='评估时间')),
            ],
            options={
                'verbose_name': '项目风险',
                'verbose_name_plural': '项目风险',
                'db_table': 'project_risks',
            },
        ),
    ]
