# Generated by Django 6.0.3 on 2026-03-31 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BidSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_type', models.CharField(choices=[('business', '商务标'), ('technical', '技术标'), ('both', '商务+技术')], max_length=20, verbose_name='投标类型')),
                ('bid_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='投标报价(万)')),
                ('period', models.IntegerField(blank=True, null=True, verbose_name='工期(天)')),
                ('payment_terms', models.TextField(blank=True, verbose_name='付款条件')),
                ('business_content', models.TextField(blank=True, verbose_name='商务标内容')),
                ('technical_content', models.TextField(blank=True, verbose_name='技术标内容')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交'), ('under_review', '审核中'), ('approved', '已通过'), ('rejected', '已驳回')], default='draft', max_length=20, verbose_name='状态')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('review_comment', models.TextField(blank=True, verbose_name='审核意见')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '投标提交',
                'verbose_name_plural': '投标提交',
                'db_table': 'bid_submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BidTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='模板名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='模板编码')),
                ('template_type', models.CharField(choices=[('business', '商务标'), ('technical', '技术标')], max_length=20, verbose_name='模板类型')),
                ('content', models.TextField(blank=True, verbose_name='模板内容')),
                ('file', models.FileField(blank=True, null=True, upload_to='templates/', verbose_name='模板文件')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '投标模板',
                'verbose_name_plural': '投标模板',
                'db_table': 'bid_templates',
            },
        ),
        migrations.CreateModel(
            name='ProjectCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='项目名称')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='项目编号')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='项目类型')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='合同金额(万)')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='开工日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='完工日期')),
                ('owner', models.CharField(blank=True, max_length=200, verbose_name='业主单位')),
                ('description', models.TextField(blank=True, verbose_name='项目描述')),
                ('result', models.CharField(blank=True, help_text='中标/未中', max_length=20, verbose_name='中标结果')),
                ('document', models.FileField(blank=True, null=True, upload_to='cases/', verbose_name='证明文件')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '业绩案例',
                'verbose_name_plural': '业绩案例',
                'db_table': 'project_cases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='资质名称')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='资质编码')),
                ('type', models.CharField(choices=[('qualification', '资质'), ('license', '许可'), ('certification', '认证')], max_length=20, verbose_name='类型')),
                ('level', models.CharField(blank=True, choices=[('special', '特级'), ('first', '一级'), ('second', '二级'), ('third', '三级')], max_length=20, verbose_name='等级')),
                ('issue_org', models.CharField(blank=True, max_length=100, verbose_name='发证机关')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='发证日期')),
                ('expire_date', models.DateField(blank=True, null=True, verbose_name='有效期至')),
                ('document', models.FileField(blank=True, null=True, upload_to='qualifications/', verbose_name='资质文件')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '企业资质',
                'verbose_name_plural': '企业资质',
                'db_table': 'qualifications',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('position', models.CharField(max_length=50, verbose_name='职位')),
                ('cert_name', models.CharField(blank=True, max_length=100, verbose_name='证书名称')),
                ('cert_no', models.CharField(blank=True, max_length=50, verbose_name='证书编号')),
                ('expire_date', models.DateField(blank=True, null=True, verbose_name='证书有效期')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/', verbose_name='简历')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否在职')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '团队人员',
                'verbose_name_plural': '团队人员',
                'db_table': 'team_members',
            },
        ),
    ]
