# Generated by Django 6.0.3 on 2026-03-31 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bidding', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bidsubmission',
            name='bidder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_submissions', to=settings.AUTH_USER_MODEL, verbose_name='投标人'),
        ),
        migrations.AddField(
            model_name='bidsubmission',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_submissions', to='projects.project', verbose_name='投标项目'),
        ),
        migrations.AddField(
            model_name='bidsubmission',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='bidding.bidtemplate', verbose_name='使用模板'),
        ),
    ]
