# Generated by Django 6.0.3 on 2026-03-31 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bidding', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20, verbose_name='版本号')),
                ('file', models.FileField(upload_to='document_versions/%Y/%m/', verbose_name='文件')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='文件大小(字节)')),
                ('comment', models.TextField(blank=True, verbose_name='版本说明')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
            ],
            options={
                'verbose_name': '文档版本',
                'verbose_name_plural': '文档版本',
                'db_table': 'document_versions',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='文件名')),
                ('file', models.FileField(upload_to='documents/%Y/%m/', verbose_name='文件')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='文件大小(字节)')),
                ('file_type', models.CharField(blank=True, max_length=50, verbose_name='文件类型')),
                ('doc_type', models.CharField(choices=[('tender', '招标文件'), ('technical', '技术方案'), ('qualification', '资质文件'), ('business', '商务文件'), ('case', '业绩材料'), ('other', '其他')], max_length=20, verbose_name='文档类型')),
                ('status', models.CharField(choices=[('processing', '处理中'), ('completed', '已完成'), ('failed', '失败')], default='completed', max_length=20, verbose_name='状态')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('bid_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='bidding.bidsubmission', verbose_name='关联投标')),
            ],
            options={
                'verbose_name': '文档',
                'verbose_name_plural': '文档',
                'db_table': 'documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
